// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma
import { defineConfig, env } from 'prisma/config';

// oxlint-disable-next-line import/no-default-export
export default defineConfig({
  schema: 'prisma/schema.prisma',
  //migrations: {
  //  path: "prisma/migrations",
  //},
  datasource: {
    url: env('DATABASE_URL'),
  },
});
