
-- Erstellt das Schema 'player' in der Datenbank 'postgres' (falls nicht vorhanden)
CREATE SCHEMA IF NOT EXISTS player;

-- Setzt den search_path auf das Schema 'player'
SET search_path TO player;


-- Enums
CREATE TYPE "PlayerStatus" AS ENUM ('ACTIVE', 'BANNED', 'DELETED');
CREATE TYPE "PlayerClass" AS ENUM ('WARRIOR', 'MAGE', 'ROGUE', 'PRIEST', 'HUNTER');

-- Tabellen
CREATE TABLE IF NOT EXISTS guild (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  description text,
  "foundedAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS player (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  level integer NOT NULL DEFAULT 1,
  experience integer NOT NULL DEFAULT 0,
  "playerClass" "PlayerClass" NOT NULL,
  status "PlayerStatus" NOT NULL DEFAULT 'ACTIVE',
  "guildId" integer REFERENCES guild(id) ON DELETE SET NULL ON UPDATE CASCADE,
  "createdAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version integer NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS player_guild_id_idx ON player("guildId");
